# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    action.yml                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: agaley <agaley@student.42lyon.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/08 01:07:00 by agaley            #+#    #+#              #
#    Updated: 2022/11/09 01:52:24 by alex             ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

name: 'libftOps'
author: 'unkn0wn107'
description: 'CI pour ta libft'

runs:
    using: composite
    steps:
      - uses: actions/checkout@v3
        with:
          path: libft

      - name: Install Francinette
        shell: bash
        run: curl -fsSL https://raw.github.com/xicodomingues/francinette/master/bin/install.sh

      - name: Run tests
        shell: bash
        run: cd libft && paco
