# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    action.yml                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: agaley <agaley@student.42lyon.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/08 01:07:00 by agaley            #+#    #+#              #
#    Updated: 2022/11/16 01:54:21 by alex             ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

name: 'libftOps'
author: 'unkn0wn107'
description: 'CI pour ta libft'

runs:
    using: composite
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'libft'

      - name: Checkout Francinette
        uses: actions/checkout@v3
        with:
          repository: 'xicodomingues/francinette'
          path: 'francinette'
          submodules: 'recursive'
          
      - name: Install apt deps
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: gcc clang libpq-dev libbsd-dev libncurses-dev valgrind python3-dev python3-venv python3-wheel python3-testresources

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install python requirements
        shell: bash
        run: |
          cd ~/francinette
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        shell: bash
        run: cd ~/libft && bash ~/francinette/tester.sh
