name: Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: Clone libftTester
        uses: actions/checkout@v2
        with:
          repository: Tripouille/libftTester
          path: libftTester

      - name: Test changed functions
        run: |
          cd libftTester
          export TERM=xterm #For tput from libftTester/Makefile
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == *.c ]]; then
              filename=${file%.*}
              make ${filename:3}
            elif [[ $file == *.h || $file == "Makefile" ]]; then
              find ../ -type f -name "*.c" -exec bash -c 'echo "$1" | sed 's/.c//' | sed 's#../ft_##' | make' - {} \; 
            fi
          done
