name: Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: Clone libftTester
        uses: actions/checkout@v2
        with:
          repository: Tripouille/libftTester

      - name: Test changed functions
        run: |
          cd libftTester
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            make ${file:3}
          done
